### ISSUE TITLE
keytool error: java.io.FileNotFoundException: /root/keys/mobileapp/key.jks (No such file or directory)

### ISSUE THREAD

**Issue by Matthcw** [parallellearning/bomdila#1]
Why must we create a signed key in order to run this project? That seems highly unnecessary, and I get the following error when falling the "To run the project" steps:

```
keytool error: java.io.FileNotFoundException: /root/keys/mobileapp/key.jks (No such file or directory)
java.io.FileNotFoundException: /root/keys/mobileapp/key.jks (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
	at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1310)
	at java.base/sun.security.tools.keytool.Main.run(Main.java:397)
	at java.base/sun.security.tools.keytool.Main.main(Main.java:390)
```
Are you sure you haven't outlined any prerequisites?

**Comment by Matthcw** [comment]
No problem, this is no longer and issue
